name: Java Test Generation

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [2]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 19.0.1
      run: sudo apt-get update && sudo apt-get install -y openjdk-19-jdk
    - name: Compile Somma.java
      run: javac Somma/src/Somma.java
    - name: Download Randoop
      run: |
            wget https://github.com/randoop/randoop/releases/download/v4.3.2/randoop-all-4.3.2.jar -P Somma/src
    - name: Unzip Emma
      run: unzip Somma/src/emma-2.0.5312.zip -d Somma/src
    - name: Controllo
      run: ls Somma/src/emma-2.0.5312
    - name: Generate Randoop tests with Emma
      run: java -classpath /home/runner/work/Somma-prova/Somma-prova/Somma/src:/home/runner/work/Somma-prova/Somma-prova/Somma/src/emma-2.0.5312/lib/emma.jar:/home/runner/work/Somma-prova/Somma-prova/Somma/src/randoop-all-4.3.2.jar randoop.main.Main gentests --testclass=Somma --output-limit=200
    - name: Emma report
      run: java -classpath /home/runner/work/Somma-prova/Somma-prova/Somma/src/emma-2.0.5312/lib/emma.jar emma report -r txt -in /home/runner/work/Somma-prova/Somma-prova/Somma/src
    - name: Controllo
      run: |
            ls 
            ls Somma
            ls Somma/src
            ls Somma/src/emma-2.0.5312/lib
            ls Somma/src/emma-2.0.5312
    - name: Upload Emma reports
      uses: actions/upload-artifact@v2
      with:
        name: Emma reports
        path: coverage.ec
