name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install JDK1.8
      run: apt-get install -y openjdk-8-jdk
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 14
    - name: Compile Somma.java
      run: javac Somma.java
    - name: Create Somma.jar
      run: jar -cvf Somma.jar Somma.class
    - name: Download Randoop
      run: wget https://randoop.github.io/randoop/releases/randoop-all-4.2.2.jar
    - name: Generate Randoop tests
      run: java -jar randoop-all-4.2.2.jar --testclass=Somma --timelimit=60 --parallel-threads=4
