name: Java Test Generation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 14
    - name: Install default-jdk
      run: apt-get install -y default-jdk
    - name: Compile Somma.java
      run: javac Somma/src/Somma.java
    - name: Download Randoop
      run: wget https://randoop.github.io/randoop/releases/randoop-all-4.2.2.jar
    - name: Generate Randoop tests
      run: java -classpath Somma/src -jar randoop-all-4.2.2.jar --testclass=Somma.Somma --timelimit=60 --parallel-threads=4
